### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [EccentricVamp/EccentricTome#20]
Forge 41.0.64+ and 41.0.94+ introduce breaking changes for eccentrictome-1.19-1.7.0-beta

java.lang.reflect.InvocationTargetException: null

[crashlog](https://github.com/EccentricVamp/EccentricTome/files/9142765/crash-2022-07-20_01.56.16-fml.txt)

**Comment by EccentricVamp** [comment]
Thanks for the heads up and the log. I'll try to investigate tomorrow and start working on a patch.

**Comment by Baggytrousers27** [comment]
¦D

**Comment by EccentricVamp** [comment]
This has been fixed by https://github.com/EccentricVamp/EccentricTome/commit/48b2750973080c6256b8f72a86350e06db238570

The fix has been released in Eccentric Tome 1.7.0-beta.1. Let me know if it solves your issue

Note: I wasn't able to use my normal set of mods for testing (they haven't been updated yet)

**Comment by Baggytrousers27** [comment]
Works beautifully. ¦D
